"""
PDF generation using reportlab — prescriptions, per-case and per-patient
summaries (for records/insurance), and date-range stat reports.

Every PDF starts with a shared letterhead (clinic name/logo/address) so the
Feast9 branding is consistent everywhere documents are printed.
"""
import io
import os
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, HRFlowable,
)
from reportlab.pdfgen import canvas as pdfcanvas

PRIMARY = colors.HexColor("#2E7D32")
PRIMARY_LIGHT = colors.HexColor("#8BC34A")
ACCENT = colors.HexColor("#E8F5E9")
TEXT = colors.HexColor("#1B2B1E")
MUTED = colors.HexColor("#5B6B5E")
BORDER = colors.HexColor("#CFE3D0")
DANGER = colors.HexColor("#C62828")

styles = getSampleStyleSheet()
styles.add(ParagraphStyle("BrandTitle", parent=styles["Heading1"], textColor=PRIMARY,
                           fontSize=18, leading=22, spaceAfter=0))
styles.add(ParagraphStyle("ClinicMeta", parent=styles["Normal"], textColor=MUTED,
                           fontSize=9, leading=12))
styles.add(ParagraphStyle("DocTitle", parent=styles["Heading2"], textColor=TEXT,
                           fontSize=14, spaceBefore=10, spaceAfter=6))
styles.add(ParagraphStyle("Label", parent=styles["Normal"], textColor=MUTED, fontSize=9))
styles.add(ParagraphStyle("Value", parent=styles["Normal"], textColor=TEXT, fontSize=11))
styles.add(ParagraphStyle("Body", parent=styles["Normal"], textColor=TEXT, fontSize=10.5,
                           leading=15))
styles.add(ParagraphStyle("Right", parent=styles["Normal"], alignment=TA_RIGHT))
styles.add(ParagraphStyle("Center", parent=styles["Normal"], alignment=TA_CENTER))
styles.add(ParagraphStyle("AllergyWarning", parent=styles["Normal"], textColor=DANGER,
                           fontSize=11, leading=14, fontName="Helvetica-Bold"))


def _logo_flowable(logo_path, max_h=22 * mm):
    if logo_path and os.path.exists(logo_path):
        try:
            img = Image(logo_path)
            ratio = img.imageWidth / img.imageHeight
            img.drawHeight = max_h
            img.drawWidth = max_h * ratio
            return img
        except Exception:
            return None
    return None


def _letterhead(clinic, logo_path):
    rows = []
    name_block = [Paragraph(clinic.get("clinic_name") or "Feast9", styles["BrandTitle"])]
    meta_bits = [b for b in [
        clinic.get("clinic_address"), clinic.get("clinic_phone"), clinic.get("clinic_email")
    ] if b]
    if meta_bits:
        name_block.append(Paragraph(" &nbsp;|&nbsp; ".join(meta_bits), styles["ClinicMeta"]))
    logo = _logo_flowable(logo_path)
    if logo:
        t = Table([[logo, name_block]], colWidths=[26 * mm, None])
        t.setStyle(TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("ALIGN", (0, 0), (0, 0), "LEFT"),
            ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ]))
        rows.append(t)
    else:
        rows.extend(name_block)
    rows.append(Spacer(1, 4))
    rows.append(HRFlowable(width="100%", thickness=1.4, color=PRIMARY_LIGHT))
    rows.append(Spacer(1, 8))
    return rows


def _info_table(pairs, col_widths=(38 * mm, None)):
    data = [[Paragraph(f"<b>{label}</b>", styles["Label"]), Paragraph(str(value or "—"), styles["Value"])]
            for label, value in pairs]
    t = Table(data, colWidths=list(col_widths))
    t.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 1),
    ]))
    return t


def _footer(text="Generated by Feast9 patient management system"):
    return [Spacer(1, 14), HRFlowable(width="100%", thickness=0.6, color=BORDER),
            Spacer(1, 4), Paragraph(text, styles["ClinicMeta"])]


def _build(buf, story, pagesize=A4, margins=18 * mm):
    doc = SimpleDocTemplate(buf, pagesize=pagesize,
                             leftMargin=margins, rightMargin=margins,
                             topMargin=margins, bottomMargin=margins)
    doc.build(story)
    return buf.getvalue()


def _money(v):
    try:
        return f"Rs. {float(v):,.2f}"
    except (TypeError, ValueError):
        return "Rs. 0.00"


# ---------------------------------------------------------------------------
# Prescription
# ---------------------------------------------------------------------------
def generate_prescription_pdf(patient: dict, case: dict, prescription: dict,
                                doctor_name: str, clinic: dict, logo_path: str = None) -> bytes:
    buf = io.BytesIO()
    story = []
    story += _letterhead(clinic, logo_path)
    story.append(Paragraph("PRESCRIPTION", styles["DocTitle"]))

    header = _info_table([
        ("Date", prescription.get("rx_date")),
        ("Patient Name", patient.get("name")),
        ("Age / Sex", f"{patient.get('age') or '—'} / {patient.get('sex') or '—'}"),
        ("Case", case.get("title")),
        ("Doctor", doctor_name or "—"),
    ])
    story.append(header)
    story.append(Spacer(1, 8))

    allergies = patient.get("allergies") or []
    allergies_other = patient.get("allergies_other") or ""
    if allergies or allergies_other:
        bits = list(allergies)
        if allergies_other:
            bits.append(allergies_other)
        warn_table = Table([[Paragraph(f"⚠ ALLERGY ALERT: {', '.join(bits)}",
                                        styles["AllergyWarning"])]], colWidths=[None])
        warn_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#FDECEA")),
            ("BOX", (0, 0), (-1, -1), 0.8, DANGER),
            ("TOPPADDING", (0, 0), (-1, -1), 7),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
            ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ]))
        story.append(warn_table)
        story.append(Spacer(1, 8))

    story.append(Spacer(1, 4))
    story.append(Paragraph("Rx", ParagraphStyle("RxLabel", parent=styles["Heading3"],
                                                  textColor=PRIMARY, fontSize=16)))
    story.append(Spacer(1, 4))
    for line in (prescription.get("rx_details") or "").split("\n"):
        story.append(Paragraph(line if line.strip() else "&nbsp;", styles["Body"]))
    story.append(Spacer(1, 40))
    sign_table = Table([[Paragraph("____________________", styles["Value"])]],
                        colWidths=[70 * mm])
    wrapper = Table([[Spacer(1, 1), sign_table]], colWidths=[None, 75 * mm])
    wrapper.setStyle(TableStyle([("ALIGN", (1, 0), (1, 0), "RIGHT")]))
    story.append(wrapper)
    story.append(Paragraph(f"<para alignment='right'>{doctor_name or 'Doctor'}</para>", styles["Value"]))
    story += _footer()
    return _build(buf, story)


# ---------------------------------------------------------------------------
# Case summary (records / insurance)
# ---------------------------------------------------------------------------
def generate_case_summary_pdf(patient: dict, case: dict, payments: list,
                                prescriptions: list, doctor_name: str, clinic: dict,
                                purpose: str = "record", logo_path: str = None,
                                amendments: list = None) -> bytes:
    buf = io.BytesIO()
    story = []
    story += _letterhead(clinic, logo_path)
    title = "CASE SUMMARY — INSURANCE CLAIM" if purpose == "insurance" else "CASE SUMMARY"
    story.append(Paragraph(title, styles["DocTitle"]))

    story.append(Paragraph("Patient Details", ParagraphStyle("Sub", parent=styles["Heading4"],
                                                               textColor=MUTED)))
    patient_rows = [
        ("Name", patient.get("name")),
        ("Age / Sex", f"{patient.get('age') or '—'} / {patient.get('sex') or '—'}"),
        ("Mobile", patient.get("mobile")),
        ("Address", patient.get("address")),
    ]
    medical_bits = list(patient.get("medical_conditions") or [])
    if patient.get("medical_conditions_other"):
        medical_bits.append(patient["medical_conditions_other"])
    if medical_bits:
        patient_rows.append(("Medical Conditions", ", ".join(medical_bits)))
    allergy_bits = list(patient.get("allergies") or [])
    if patient.get("allergies_other"):
        allergy_bits.append(patient["allergies_other"])
    if allergy_bits:
        patient_rows.append(("Allergies", ", ".join(allergy_bits)))
    if patient.get("is_pregnant") or patient.get("is_nursing"):
        status_bits = []
        if patient.get("is_pregnant"):
            status_bits.append("Pregnant")
        if patient.get("is_nursing"):
            status_bits.append("Nursing")
        patient_rows.append(("Status", ", ".join(status_bits)))
    story.append(_info_table(patient_rows))
    story.append(Spacer(1, 10))

    story.append(Paragraph("Case Details", ParagraphStyle("Sub2", parent=styles["Heading4"],
                                                            textColor=MUTED)))
    procedures = ", ".join(case.get("procedures") or []) or "—"
    if case.get("custom_procedure"):
        procedures += f" ({case['custom_procedure']})"
    story.append(_info_table([
        ("Case Title", case.get("title")),
        ("Status", case.get("status")),
        ("Procedures", procedures),
        ("Treating Doctor", doctor_name or "—"),
        ("Case Opened", case.get("created_at")),
        ("Case Closed", case.get("closed_at") or "—"),
    ]))
    story.append(Spacer(1, 10))

    total_cost = case.get("total_cost", 0)
    total_paid = sum(p["amount"] for p in payments)
    balance = round(total_cost - total_paid, 2)

    story.append(Paragraph("Cost Details", ParagraphStyle("Sub3", parent=styles["Heading4"],
                                                            textColor=MUTED)))
    cost_table = Table([
        ["Total Treatment Cost", _money(total_cost)],
        ["Total Paid", _money(total_paid)],
        ["Balance Due" if case.get("status") == "Active" else "Balance at Closure", _money(balance)],
    ], colWidths=[80 * mm, 50 * mm])
    cost_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 10.5),
        ("ALIGN", (1, 0), (1, -1), "RIGHT"),
        ("LINEBELOW", (0, 0), (-1, -2), 0.4, BORDER),
        ("LINEABOVE", (0, -1), (-1, -1), 0.8, PRIMARY),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
    ]))
    story.append(cost_table)
    story.append(Spacer(1, 10))

    if amendments:
        story.append(Paragraph("Cost Revision History", ParagraphStyle("Sub3b", parent=styles["Heading4"],
                                                                         textColor=MUTED)))
        data = [["Date", "Previous", "Revised To", "Reason"]]
        for a in sorted(amendments, key=lambda x: x["amended_at"]):
            data.append([a["amended_at"], _money(a["previous_cost"]), _money(a["new_cost"]),
                         a.get("reason") or ""])
        at = Table(data, colWidths=[24 * mm, 26 * mm, 26 * mm, None])
        at.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("ALIGN", (1, 1), (2, -1), "RIGHT"),
            ("GRID", (0, 0), (-1, -1), 0.4, BORDER),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, ACCENT]),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(at)
        story.append(Spacer(1, 10))

    if payments:
        story.append(Paragraph("Payment History", ParagraphStyle("Sub4", parent=styles["Heading4"],
                                                                   textColor=MUTED)))
        data = [["Date", "Amount", "Method", "Note"]]
        for p in payments:
            data.append([p["payment_date"], _money(p["amount"]), p.get("method") or "—",
                         p.get("note") or ""])
        pt = Table(data, colWidths=[28 * mm, 30 * mm, 28 * mm, None])
        pt.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 9.5),
            ("ALIGN", (1, 1), (1, -1), "RIGHT"),
            ("GRID", (0, 0), (-1, -1), 0.4, BORDER),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, ACCENT]),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(pt)
        story.append(Spacer(1, 10))

    if prescriptions:
        story.append(Paragraph("Prescription History", ParagraphStyle("Sub5", parent=styles["Heading4"],
                                                                        textColor=MUTED)))
        for rx in prescriptions:
            rx_html = (rx['rx_details'] or "").replace("\n", "<br/>")
            story.append(Paragraph(f"<b>{rx['rx_date']}</b> — {rx_html}", styles["Body"]))
            story.append(Spacer(1, 4))

    if purpose == "insurance":
        story.append(Spacer(1, 10))
        story.append(Paragraph(
            "This document summarizes the treatment case and associated costs for "
            "insurance claim / reimbursement purposes.", styles["ClinicMeta"]))

    story += _footer()
    return _build(buf, story)


# ---------------------------------------------------------------------------
# Patient summary (all cases)
# ---------------------------------------------------------------------------
def generate_patient_summary_pdf(patient: dict, cases: list, clinic: dict,
                                   logo_path: str = None) -> bytes:
    buf = io.BytesIO()
    story = []
    story += _letterhead(clinic, logo_path)
    story.append(Paragraph("PATIENT SUMMARY", styles["DocTitle"]))
    story.append(_info_table([
        ("Name", patient.get("name")),
        ("Age / Sex", f"{patient.get('age') or '—'} / {patient.get('sex') or '—'}"),
        ("Mobile", patient.get("mobile")),
        ("Email", patient.get("email") or "—"),
        ("Address", patient.get("address")),
        ("Last Visited", patient.get("last_visited_date") or "—"),
    ]))
    story.append(Spacer(1, 12))
    story.append(Paragraph("Treatment Cases", ParagraphStyle("Sub", parent=styles["Heading4"],
                                                               textColor=MUTED)))

    data = [["Title", "Status", "Doctor", "Cost", "Paid", "Balance", "Opened"]]
    for c in cases:
        data.append([
            c.get("title"), c.get("status"), c.get("doctor_name") or "—",
            _money(c.get("total_cost")), _money(c.get("paid")), _money(c.get("balance")),
            c.get("created_at"),
        ])
    t = Table(data, colWidths=[42 * mm, 18 * mm, 28 * mm, 22 * mm, 22 * mm, 22 * mm, None])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("ALIGN", (3, 1), (5, -1), "RIGHT"),
        ("GRID", (0, 0), (-1, -1), 0.4, BORDER),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, ACCENT]),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(t)
    story += _footer()
    return _build(buf, story)


# ---------------------------------------------------------------------------
# Date-range report
# ---------------------------------------------------------------------------
def generate_report_pdf(start_date: str, end_date: str, stats: dict, payments: list,
                          closed_cases: list, clinic: dict, logo_path: str = None,
                          revenue_summary: dict = None) -> bytes:
    buf = io.BytesIO()
    story = []
    story += _letterhead(clinic, logo_path)
    story.append(Paragraph("PRACTICE REPORT", styles["DocTitle"]))
    story.append(Paragraph(f"Period: {start_date} to {end_date}", styles["ClinicMeta"]))
    story.append(Spacer(1, 10))

    if revenue_summary:
        story.append(Paragraph("Revenue Overview — All Time", ParagraphStyle(
            "RevSub", parent=styles["Heading4"], textColor=MUTED)))
        rev_data = [
            ["Total Billed", "Total Collected", "Total Pending", "Collection Rate"],
            [
                _money(revenue_summary["total_billed"]),
                _money(revenue_summary["total_collected"]),
                _money(revenue_summary["total_pending"]),
                f"{revenue_summary['collection_rate']}%",
            ],
        ]
        rt = Table(rev_data, colWidths=[None]*4)
        rt.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (-1,0), PRIMARY),
            ("TEXTCOLOR", (0,0), (-1,0), colors.white),
            ("FONTSIZE", (0,0), (-1,-1), 9),
            ("ALIGN", (0,0), (-1,-1), "CENTER"),
            ("GRID", (0,0), (-1,-1), 0.4, BORDER),
            ("BACKGROUND", (0,1), (-1,1), ACCENT),
            ("FONTSIZE", (0,1), (-1,1), 10),
            ("FONTNAME", (0,1), (-1,1), "Helvetica-Bold"),
            ("TOPPADDING", (0,0), (-1,-1), 6),
            ("BOTTOMPADDING", (0,0), (-1,-1), 6),
        ]))
        story.append(rt)
        story.append(Spacer(1, 10))

    summary_data = [
        ["Revenue Collected", _money(stats.get("revenue", 0))],
        ["Cases Closed", str(stats.get("cases_closed", 0))],
        ["New Cases Opened", str(stats.get("new_cases", 0))],
        ["New Patients Registered", str(stats.get("new_patients", 0))],
    ]
    st = Table(summary_data, colWidths=[80 * mm, 50 * mm])
    st.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 11),
        ("ALIGN", (1, 0), (1, -1), "RIGHT"),
        ("BACKGROUND", (0, 0), (-1, -1), ACCENT),
        ("BOX", (0, 0), (-1, -1), 0.6, BORDER),
        ("INNERGRID", (0, 0), (-1, -1), 0.4, BORDER),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
    ]))
    story.append(st)
    story.append(Spacer(1, 14))

    if payments:
        story.append(Paragraph(f"Payments received ({len(payments)})",
                                ParagraphStyle("Sub", parent=styles["Heading4"], textColor=MUTED)))
        data = [["Date", "Patient", "Case", "Amount"]]
        for p in payments[:500]:
            data.append([p["payment_date"], p.get("patient_name", ""), p.get("case_title", ""),
                         _money(p["amount"])])
        pt = Table(data, colWidths=[24 * mm, 40 * mm, 50 * mm, None])
        pt.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 8.5),
            ("ALIGN", (3, 1), (3, -1), "RIGHT"),
            ("GRID", (0, 0), (-1, -1), 0.4, BORDER),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, ACCENT]),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ]))
        story.append(pt)
        if len(payments) > 500:
            story.append(Paragraph(f"...and {len(payments) - 500} more (see CSV export for the full list).",
                                    styles["ClinicMeta"]))
        story.append(Spacer(1, 12))

    if closed_cases:
        story.append(Paragraph(f"Cases closed ({len(closed_cases)})",
                                ParagraphStyle("Sub2", parent=styles["Heading4"], textColor=MUTED)))
        data = [["Closed On", "Patient", "Case", "Total Cost"]]
        for c in closed_cases[:500]:
            data.append([c["closed_at"], c.get("patient_name", ""), c["title"], _money(c["total_cost"])])
        ct = Table(data, colWidths=[24 * mm, 40 * mm, 50 * mm, None])
        ct.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 8.5),
            ("ALIGN", (3, 1), (3, -1), "RIGHT"),
            ("GRID", (0, 0), (-1, -1), 0.4, BORDER),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, ACCENT]),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ]))
        story.append(ct)

    story += _footer()
    return _build(buf, story)


# ---------------------------------------------------------------------------
# Consent form
# ---------------------------------------------------------------------------
def generate_consent_pdf(patient: dict, case: dict, consent: dict, doctor_name: str,
                           clinic: dict, logo_path: str = None,
                           signature_image_path: str = None, blank: bool = False) -> bytes:
    buf = io.BytesIO()
    story = []
    story += _letterhead(clinic, logo_path)
    story.append(Paragraph("TREATMENT CONSENT FORM", styles["DocTitle"]))

    story.append(_info_table([
        ("Patient Name", patient.get("name")),
        ("Age / Sex", f"{patient.get('age') or '—'} / {patient.get('sex') or '—'}"),
        ("Case", case.get("title")),
        ("Doctor", doctor_name or "—"),
        ("Date", consent.get("signed_date") or "________________"),
    ]))
    story.append(Spacer(1, 12))

    for para in (consent.get("consent_text") or "").split("\n\n"):
        line_html = para.replace("\n", "<br/>")
        story.append(Paragraph(line_html, styles["Body"]))
        story.append(Spacer(1, 8))

    story.append(Spacer(1, 20))

    if blank:
        sig_cell = Paragraph("_____________________________", styles["Value"])
    elif signature_image_path and os.path.exists(signature_image_path):
        try:
            sig_img = Image(signature_image_path)
            ratio = sig_img.imageWidth / sig_img.imageHeight
            sig_img.drawHeight = 18 * mm
            sig_img.drawWidth = 18 * mm * ratio
            if sig_img.drawWidth > 70 * mm:
                sig_img.drawWidth = 70 * mm
                sig_img.drawHeight = 70 * mm / ratio
            sig_cell = sig_img
        except Exception:
            sig_cell = Paragraph("_____________________________", styles["Value"])
    else:
        sig_cell = Paragraph("(signed copy on file — see attachment)", styles["ClinicMeta"])

    sign_table = Table(
        [[sig_cell], [Paragraph("Patient / Guardian Signature", styles["Label"])]],
        colWidths=[80 * mm],
    )
    sign_table.setStyle(TableStyle([
        ("ALIGN", (0, 0), (-1, -1), "LEFT"),
        ("TOPPADDING", (0, 1), (0, 1), 2),
        ("LINEBELOW", (0, 0), (0, 0), 0.6, BORDER),
    ]))
    story.append(sign_table)
    story.append(Spacer(1, 10))

    if consent.get("witness_name"):
        story.append(Paragraph(f"<b>Witness:</b> {consent['witness_name']}", styles["Body"]))
    if consent.get("notes"):
        story.append(Paragraph(f"<b>Notes:</b> {consent['notes']}", styles["Body"]))

    story += _footer()
    return _build(buf, story)


# ---------------------------------------------------------------------------
# DPDP Phase 2 — Right to Access: full data export PDF
# ---------------------------------------------------------------------------
def generate_data_access_pdf(patient: dict, cases: list, payments_by_case: dict,
                               prescriptions_by_case: dict, consents_by_case: dict,
                               appointments: list, clinic: dict,
                               logo_path: str = None) -> bytes:
    """Generates a comprehensive export of all data held on a patient —
    the response to a Right to Access request under Section 11, DPDP Act 2023."""
    buf = io.BytesIO()
    story = []
    story += _letterhead(clinic, logo_path)
    story.append(Paragraph("PATIENT DATA EXPORT", styles["DocTitle"]))
    story.append(Paragraph(
        "This document contains all personal and clinical data held by this practice "
        "about the patient named below. It is issued in response to a Right to Access "
        "request under Section 11, Digital Personal Data Protection Act 2023.",
        styles["ClinicMeta"]))
    story.append(Spacer(1, 10))

    # Personal details
    story.append(Paragraph("Personal Details", ParagraphStyle(
        "Sub", parent=styles["Heading4"], textColor=MUTED)))
    story.append(_info_table([
        ("Name",              patient.get("name")),
        ("Age / Sex",         f"{patient.get('age') or '—'} / {patient.get('sex') or '—'}"),
        ("Mobile",            patient.get("mobile")),
        ("Email",             patient.get("email") or "—"),
        ("Address",           patient.get("address") or "—"),
        ("Last Visited",      patient.get("last_visited_date") or "—"),
        ("Emergency Contact", f"{patient.get('emergency_contact_name') or '—'}"
                              f" ({patient.get('emergency_contact_relation') or '—'})"
                              f" {patient.get('emergency_contact_number') or ''}"),
    ]))
    story.append(Spacer(1, 8))

    # Medical history
    conds = patient.get("medical_conditions") or []
    allergies = patient.get("allergies") or []
    story.append(Paragraph("Medical History on File", ParagraphStyle(
        "Sub2", parent=styles["Heading4"], textColor=MUTED)))
    story.append(_info_table([
        ("Conditions",      ", ".join(conds) or "None recorded"),
        ("Other notes",     patient.get("medical_conditions_other") or "—"),
        ("Allergies",       ", ".join(allergies) or "None recorded"),
        ("Other allergies", patient.get("allergies_other") or "—"),
        ("Pregnant",        "Yes" if patient.get("is_pregnant") else "No"),
        ("Nursing",         "Yes" if patient.get("is_nursing") else "No"),
    ]))
    story.append(Spacer(1, 8))

    # Consent status
    story.append(Paragraph("Consent Records", ParagraphStyle(
        "Sub3", parent=styles["Heading4"], textColor=MUTED)))
    story.append(_info_table([
        ("Data Processing Notice", "Acknowledged" if patient.get("dpdp_notice_accepted")
                                   else "Not yet acknowledged"),
        ("Notice Acknowledged At", patient.get("dpdp_notice_accepted_at") or "—"),
        ("Communications Consent", "Yes" if patient.get("comms_consent") else "No (opted out)"),
    ]))
    story.append(Spacer(1, 10))

    # Treatment cases
    if cases:
        story.append(Paragraph("Treatment Cases", ParagraphStyle(
            "Sub4", parent=styles["Heading4"], textColor=MUTED)))
        for c in cases:
            story.append(Paragraph(f"<b>{c['title']}</b> — {c['status']}",
                                    styles["Body"]))
            procs = ", ".join(c.get("procedures") or []) or "—"
            story.append(_info_table([
                ("Doctor",     c.get("doctor_name") or "—"),
                ("Procedures", procs),
                ("Total Cost", _money(c.get("total_cost", 0))),
                ("Opened",     c.get("created_at") or "—"),
                ("Closed",     c.get("closed_at") or "—"),
            ], col_widths=(30 * mm, None)))
            # Payments for this case
            pmts = payments_by_case.get(c["id"], [])
            if pmts:
                pmt_data = [["Date", "Amount", "Method"]]
                for p in pmts:
                    pmt_data.append([p["payment_date"], _money(p["amount"]),
                                      p.get("method") or "—"])
                pt = Table(pmt_data, colWidths=[24*mm, 28*mm, 28*mm])
                pt.setStyle(TableStyle([
                    ("BACKGROUND", (0,0), (-1,0), PRIMARY),
                    ("TEXTCOLOR", (0,0), (-1,0), colors.white),
                    ("FONTSIZE", (0,0), (-1,-1), 8),
                    ("GRID", (0,0), (-1,-1), 0.4, BORDER),
                    ("ROWBACKGROUNDS", (0,1), (-1,-1), [colors.white, ACCENT]),
                    ("TOPPADDING", (0,0), (-1,-1), 3),
                    ("BOTTOMPADDING", (0,0), (-1,-1), 3),
                ]))
                story.append(pt)
            # Prescriptions
            rxs = prescriptions_by_case.get(c["id"], [])
            for rx in rxs:
                rx_html = (rx['rx_details'] or "").replace("\n", "<br/>")
                story.append(Paragraph(f"<b>Rx {rx['rx_date']}:</b> {rx_html}",
                                        styles["Body"]))
            story.append(Spacer(1, 8))

    # Appointments
    if appointments:
        story.append(Paragraph("Appointments", ParagraphStyle(
            "Sub5", parent=styles["Heading4"], textColor=MUTED)))
        data = [["Date", "Time", "Doctor", "Reason", "Status"]]
        for a in appointments:
            data.append([a["appt_date"], a["start_time"],
                          a.get("doctor_name") or "—",
                          a.get("title") or "—", a.get("status") or "—"])
        at = Table(data, colWidths=[22*mm, 16*mm, 32*mm, 40*mm, 22*mm])
        at.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (-1,0), PRIMARY),
            ("TEXTCOLOR", (0,0), (-1,0), colors.white),
            ("FONTSIZE", (0,0), (-1,-1), 8),
            ("GRID", (0,0), (-1,-1), 0.4, BORDER),
            ("ROWBACKGROUNDS", (0,1), (-1,-1), [colors.white, ACCENT]),
            ("TOPPADDING", (0,0), (-1,-1), 3),
            ("BOTTOMPADDING", (0,0), (-1,-1), 3),
        ]))
        story.append(at)
        story.append(Spacer(1, 8))

    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", thickness=0.6, color=BORDER))
    story.append(Spacer(1, 4))
    story.append(Paragraph(
        f"Export generated on {__import__('datetime').date.today().isoformat()} in response to "
        "a Right to Access request (Section 11, DPDP Act 2023). "
        "Retention period: clinical records 7 years from last visit; "
        "communications data as long as necessary.",
        styles["ClinicMeta"]))
    story += _footer()
    return _build(buf, story)
